export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_NEWS_FEED = 'GET_NEWS_FEED';

export const TOGGLE_TWEET_POPUP = 'TOGGLE_TWEET_POPUP';
export const TOGGLE_REPLY_POPUP = 'TOGGLE_REPLY_POPUP';
export const TOGGLE_ACTIVITY_POPUP = 'TOGGLE_ACTIVITY_POPUP';
export const TOGGLE_EDIT_POPUP = 'TOGGLE_EDIT_POPUP';

export const GET_TWEET = 'GET_TWEET';
export const NEW_TWEET = 'NEW_TWEET';
export const REPLY_TWEET = 'REPLY_TWEET';
export const DELETE_TWEET = 'DELETE_TWEET';
export const DELETE_REPLY = 'DELETE_REPLY';

export const GET_LIKES = 'GET_LIKES';
export const ADD_LIKE = 'ADD_LIKE';
export const ADD_LIKE_TO_NEWSFEED = 'ADD_LIKE_TO_NEWSFEED';
export const REMOVE_LIKE_TO_NEWSFEED = 'REMOVE_LIKE_TO_NEWSFEED';
export const REMOVE_LIKE = 'REMOVE_LIKE';
export const ADD_LIKE_TO_TWEET = 'ADD_LIKE_TO_TWEET';
export const REMOVE_LIKE_TO_TWEET = 'REMOVE_LIKE_TO_TWEET';

export const GET_RETWEETS = 'GET_RETWEETS';
export const RETWEET = 'RETWEET';
export const ADD_RETWEET_TO_NEWSFEED = 'ADD_RETWEET_TO_NEWSFEED';
export const REMOVE_RETWEET = 'REMOVE_RETWEET';
export const REMOVE_RETWEET_TO_NEWSFEED = 'REMOVE_RETWEET_TO_NEWSFEED';
export const ADD_RETWEET_TO_TWEET = 'ADD_RETWEET_TO_TWEET';
export const REMOVE_RETWEET_TO_TWEET = 'REMOVE_RETWEET_TO_TWEET';

export const GET_USERS = 'GET_USERS';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_TWEETS = 'GET_PROFILE_TWEETS';
export const EDIT_PROFILE = 'EDIT_PROFILE';

export const GET_FOLLOWINGS = 'GET_FOLLOWINGS';
export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';